# Generated by Django 4.2 on 2024-01-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
    ]
